{
 "title": "Device Performance",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "flow_name",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: v.bucket,\n    tag: \"flow_id\"\n)"
   },
   {
    "name": "app_version",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: v.bucket,\n    tag: \"app_version\"\n)"
   },
   {
    "name": "os_version",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: v.bucket,\n    tag: \"os_version\"\n)"
   },
   {
    "name": "device_name",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: v.bucket,\n    tag: \"device_name\"\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Execution time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"execution_time\")\n  |> filter(fn: (r) => r[\"flow_id\"] =~ /^${flow_name:regex}/)\n  |> filter(fn: (r) => r[\"app_version\"] =~ /^${app_version:regex}/)\n  |> filter(fn: (r) => r[\"os_version\"] =~ /^${os_version:regex}/)\n  |> filter(fn: (r) => r[\"device_name\"] =~ /^${device_name:regex}/)\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "CPU resources over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"flow_id\"] =~ /^${flow_name:regex}/)\n  |> filter(fn: (r) => r[\"app_version\"] =~ /^${app_version:regex}/)\n  |> filter(fn: (r) => r[\"os_version\"] =~ /^${os_version:regex}/)\n  |> filter(fn: (r) => r[\"device_name\"] =~ /^${device_name:regex}/)\n  |> group(columns: [\"actionName\", \"elementName\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\nfrom(bucket: \"carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"flow_id\"] =~ /^${flow_name:regex}/)\n  |> filter(fn: (r) => r[\"app_version\"] =~ /^${app_version:regex}/)\n  |> filter(fn: (r) => r[\"os_version\"] =~ /^${os_version:regex}/)\n  |> filter(fn: (r) => r[\"device_name\"] =~ /^${device_name:regex}/)\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "CPU usage (mean)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"flow_id\"] =~ /^${flow_name:regex}/)\n  |> filter(fn: (r) => r[\"app_version\"] =~ /^${app_version:regex}/)\n  |> filter(fn: (r) => r[\"os_version\"] =~ /^${os_version:regex}/)\n  |> filter(fn: (r) => r[\"device_name\"] =~ /^${device_name:regex}/)\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Memory resources over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\n  |> filter(fn: (r) => r[\"flow_id\"] =~ /^${flow_name:regex}/)\n  |> filter(fn: (r) => r[\"app_version\"] =~ /^${app_version:regex}/)\n  |> filter(fn: (r) => r[\"os_version\"] =~ /^${os_version:regex}/)\n  |> filter(fn: (r) => r[\"device_name\"] =~ /^${device_name:regex}/)\n  |> group(columns: [\"actionName\", \"elementName\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\nfrom(bucket: \"carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\n  |> filter(fn: (r) => r[\"flow_id\"] =~ /^${flow_name:regex}/)\n  |> filter(fn: (r) => r[\"app_version\"] =~ /^${app_version:regex}/)\n  |> filter(fn: (r) => r[\"os_version\"] =~ /^${os_version:regex}/)\n  |> filter(fn: (r) => r[\"device_name\"] =~ /^${device_name:regex}/)\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Memory usage (mean)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\n  |> filter(fn: (r) => r[\"flow_id\"] =~ /^${flow_name:regex}/)\n  |> filter(fn: (r) => r[\"app_version\"] =~ /^${app_version:regex}/)\n  |> filter(fn: (r) => r[\"os_version\"] =~ /^${os_version:regex}/)\n  |> filter(fn: (r) => r[\"device_name\"] =~ /^${device_name:regex}/)\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Load time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Load time after action",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"load_time\")\n  |> filter(fn: (r) => r[\"flow_id\"] =~ /^${flow_name:regex}/)\n  |> filter(fn: (r) => r[\"app_version\"] =~ /^${app_version:regex}/)\n  |> filter(fn: (r) => r[\"os_version\"] =~ /^${os_version:regex}/)\n  |> filter(fn: (r) => r[\"device_name\"] =~ /^${device_name:regex}/)\n  |> group(columns: [\"actionName\", \"elementName\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\nfrom(bucket: \"carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"load_time\")\n  |> filter(fn: (r) => r[\"flow_id\"] =~ /^${flow_name:regex}/)\n  |> filter(fn: (r) => r[\"app_version\"] =~ /^${app_version:regex}/)\n  |> filter(fn: (r) => r[\"os_version\"] =~ /^${os_version:regex}/)\n  |> filter(fn: (r) => r[\"device_name\"] =~ /^${device_name:regex}/)\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Load Time (Mean)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"load_time\")\n  |> filter(fn: (r) => r[\"flow_id\"] =~ /^${flow_name:regex}/)\n  |> filter(fn: (r) => r[\"app_version\"] =~ /^${app_version:regex}/)\n  |> filter(fn: (r) => r[\"os_version\"] =~ /^${os_version:regex}/)\n  |> filter(fn: (r) => r[\"device_name\"] =~ /^${device_name:regex}/)\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "GPU Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Frames rendered",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gfx\")\n  |> filter(fn: (r) => r[\"flow_id\"] =~ /^${flow_name:regex}/)\n  |> filter(fn: (r) => r[\"app_version\"] =~ /^${app_version:regex}/)\n  |> filter(fn: (r) => r[\"os_version\"] =~ /^${os_version:regex}/)\n  |> filter(fn: (r) => r[\"device_name\"] =~ /^${device_name:regex}/)\n  |> filter(fn: (r) => r[\"_field\"] == \"total_frames\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gfx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"janky_frames\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    { "expression": "$B/$A*100", "type": "math" }
   ]
  },
  {
   "title": "Frame rendering time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gfx\")\n  |> filter(fn: (r) => r[\"flow_id\"] =~ /^${flow_name:regex}/)\n  |> filter(fn: (r) => r[\"app_version\"] =~ /^${app_version:regex}/)\n  |> filter(fn: (r) => r[\"os_version\"] =~ /^${os_version:regex}/)\n  |> filter(fn: (r) => r[\"device_name\"] =~ /^${device_name:regex}/)\n  |> filter(fn: (r) => r[\"_field\"] == \"99_percentile\" or r[\"_field\"] == \"95_percentile\" or r[\"_field\"] == \"90_percentile\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n  "
    }
   ]
  },
  {
   "title": "Net stats",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\n  |> filter(fn: (r) => r[\"flow_id\"] =~ /^${flow_name:regex}/)\n  |> filter(fn: (r) => r[\"app_version\"] =~ /^${app_version:regex}/)\n  |> filter(fn: (r) => r[\"os_version\"] =~ /^${os_version:regex}/)\n  |> filter(fn: (r) => r[\"device_name\"] =~ /^${device_name:regex}/)\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}